import turtle
length=int(input("Enter an even integer between 50 and 500: "))
window=turtle.Screen()
window.bgcolor("gold")
plus = turtle.Turtle()
plus.hideturtle()
plus.pencolor("blue")
plus.pensize(20)
num= float(length)/2.0
plus.penup()
plus.backward(num)
plus.pendown()
plus.forward(length)
plus.penup()
plus.setx(0)
plus.sety(length/2)
plus.pendown()
plus.right(90)
plus.forward(length)
